---
title: "5-fold CV"
author: "Alyssa"
date: "`r Sys.Date()`"
output:
  html_notebook:
    code_folding: hide
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, message=FALSE}
## set working directory to script location
current_directory <- dirname(rstudioapi::getActiveDocumentContext()$path)
knitr::opts_knit$set(root.dir=normalizePath(paste0(current_directory)))

## set global chunk options
knitr::opts_chunk$set()
```

```{r warning=FALSE, message=FALSE}
## load libraries
library(DSS)
library(caret)
library(glmnet)
library(glmnetUtils)
library(ggpubr)
library(tidyverse)
```

```{r}
## specify function to filter a single sample based on significantly related sites
filter_sample <- function(sample_data, sig_sites) {
  sample_data %>%
    inner_join(sig_sites, by = c("seqid" = "chr", "start" = "pos"))
}
```

```{r}
### Prepare data ----

## read in data (pre-filtered based on CpG sites common to all samples)
barcode_list_filtered <- readRDS("dataFiles/barcode_list_filtered2.rds")

## extract age information
pheno_data <- data.frame(sample = character(), age = numeric())

for (sample_name in names(barcode_list_filtered)) {
  sample_age <- barcode_list_filtered[[sample_name]]$age[1]
  pheno_data <- rbind(pheno_data, data.frame(sample = sample_name, age = sample_age))
}

## create empty list for dss info
dss_list <- list()

## fill vector and list based on barcode_list_filtered
for (i in seq_along(barcode_list_filtered)) {
  
  ## get sample name
  sample_name <- names(barcode_list_filtered)[i] 
  
  ## get dss info
  dss_temp <- barcode_list_filtered[[i]] %>% 
    rename(chr = seqid, pos = start, N = cov, X = n_mod) %>% 
    select(chr, pos, N, X) %>% 
    mutate(N = as.numeric(N), X = as.numeric(X), pos = as.numeric(pos)) %>%
    ## sort by chromosome and position 
    arrange(chr, pos)
  
  ## add to list by name
  dss_list[[sample_name]] <- dss_temp 
  
}
```

```{r warning=FALSE}
## create BSseqData
bs_obj <- makeBSseqData(dss_list, names(dss_list))
```

## Perform 5-fold CV (cross-validation)

NB: technically this is nested CV because we are also performing "inner" CV to tune the penalty (lambda) using cv.glmnet

```{r message=FALSE, warning=FALSE}
### Perform 5-fold nested cv ----

set.seed(1234)

## specify alpha (0.5 for elastic net)
alpha_spec <- 0.5

## create 5-fold cv sample indices based on the values of age
sample_indices <- createFolds(y=pheno_data$age, 
            k = 5, 
            returnTrain = TRUE)

## to store results
pheno_outercv <- NULL
predictive_sites_5foldcv <- NULL

## begin outer cv loop
for (i in seq_along(sample_indices)) {

  ### Step 1. Split data into testing and training folds ----
  
  ## use the sample_index to subset the training data
  pheno_train <- pheno_data[sample_indices[[i]], ]
  
  ## use the inverse sample_index to subset the testing data
  pheno_test <- pheno_data[-sample_indices[[i]], ]
  
  ## do the same for the methylation data
  bs_obj_train <- bs_obj[, pheno_train$sample]

  ### Step 2. Identify significantly associated sites (filter features) ----
  
  ## fit linear model to the training data only (for modelling)
  dml_fit_train <- DMLfit.multiFactor(bs_obj_train, 
                                      design=data.frame(age=pheno_train$age), 
                                      formula=~age, 
                                      smoothing=TRUE) 

  ## test effect of age
  dml_train <- DMLtest.multiFactor(dml_fit_train, term = "age") ## (for modelling)
  
  ## filter for significantly associated sites
  sig_sites_train <- dml_train %>% filter(fdrs < 0.05) ## (for modelling)

  ## use function to filter sample data for significantly associated sites
  barcode_list_filtered_ss <- lapply(barcode_list_filtered, filter_sample, sig_sites = sig_sites_train)

  ## extract methylation data for each sample and site
  meth_data <- NULL

  for (sample_name in names(barcode_list_filtered_ss)) {
    
    sample_data <- barcode_list_filtered_ss[[sample_name]]
    
    sample_data <- sample_data %>%
      mutate(sample = sample_name)
    
    sample_wide <- sample_data %>%
      unite("id", c("seqid", "start", "end"), sep = "_") %>%
      select(sample, id, frac_mod) %>%
      spread(key = id, value = frac_mod)
    
    meth_data <- bind_rows(meth_data, sample_wide)
  }

  ## convert to matrix for modelling
  meth_data <- meth_data %>%
    column_to_rownames(var="sample") %>%
    as.matrix(.)

  ## split into test and train
  meth_train <- data.matrix(meth_data[pheno_train$sample, ])
  meth_test <- data.matrix(meth_data[pheno_test$sample, ])

  ### Step 3. Perform inner cross validation to optimise lambda (training data only) ----

  ## cross validate alpha and lambda
  cross_validation <- cv.glmnet(x=meth_train, y=pheno_train$age)
  
  ## get lambda 1se
  lambda_1se <- cross_validation$lambda.1se

  ### Step 4. Build the model (training data only) ----
  
  ## fit a glm with elastic net regularization to the training data
  model <- glmnet(meth_train,
                  pheno_train$age, 
                  family="gaussian",
                  lambda=lambda_1se,
                  alpha=alpha_spec)
  
  ## predict for training data
  pheno_train <- pheno_train %>%
    mutate(predicted_age = predict(model, 
                                   meth_train, 
                                   type="response",
                                   s=lambda_1se)[,'s1']) %>%
    mutate(absolute_error = abs(age - predicted_age), 
           data_split = "Training data", 
           mae = mean(absolute_error))
  
  ## predict for test data
  pheno_test <- pheno_test %>%
    mutate(predicted_age = predict(model, 
                                   meth_test, 
                                   type="response",
                                   s=lambda_1se)[,'s1']) %>%
    mutate(absolute_error = abs(age - predicted_age), 
           data_split = "Test data", 
           mae = mean(absolute_error))
  
  ## combine
  pheno_outercv <- rbind(pheno_outercv, 
                         (full_join(pheno_train, pheno_test) %>%
                            mutate(iteration = i, # names(sample_indices[i]),
                                   lambda = lambda_1se)))
  
  
  ## extract the coefficients for the predictive sites
  predictive_sites <- data.frame(as.matrix(coef(model, s=lambda_1se))) %>%
    filter(s1 != 0) %>%
    rownames_to_column(., var="id") %>%
    ## remove intercept
    filter(id != "(Intercept)") %>%
    ## reformat locations
    extract(id, into = c("seqid", "start", "end"),
            regex = "(NW_\\d+\\.\\d+)_(\\d+)_(\\d+)", 
            remove=FALSE, convert = TRUE) %>%
    ## rename coefficient column
    rename(coefficient = s1) %>%
    ## add identifiers
    mutate(cv_type = "5-foldCV", 
           iteration = i)
  
  ## combine
  predictive_sites_5foldcv <- rbind(predictive_sites_5foldcv,
                                predictive_sites)
  
}
```

```{r}
## predicted ~ observed plot
outercv_test_results <- pheno_outercv %>%
  filter(data_split == "Test data")

min_val <- min(c(outercv_test_results$age, outercv_test_results$predicted_age))
max_val <- max(c(outercv_test_results$age, outercv_test_results$predicted_age))

c <- ggplot(outercv_test_results, aes(x=age, y=predicted_age))+
  geom_point(alpha = 0.5) + 
  geom_smooth(method = "lm") +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "grey")+
  lims(x=c(min_val, max_val),
       y=c(min_val, max_val))+
  labs(x = "Observed age (years)", y = "Predicted age (years)") +
  theme_bw()+
  stat_cor(label.x.npc = "left", label.y.npc = "top", method = "pearson",
           aes(label = paste(after_stat(rr.label), after_stat(p.label), sep = "~`,`~")))
  # stat_regline_equation(label.x.npc = "left", label.y.npc = "top") ## option for equation

# c
```

```{r}
## absolute error plot
e <- ggplot(outercv_test_results, aes(x = age, y = absolute_error)) +
  geom_point(alpha=0.5)+
  geom_smooth(method = "lm", formula = y ~ poly(x, 2)) +
  labs(x = "Observed age (years)",
       y = "Absolute error (years)")+
  lims(x=c(min(outercv_test_results$age), max(outercv_test_results$age)),
       y=c(-0.1,1))+
  annotate("text", x = 1, y = 1, 
           label = paste0("MAE: ", round(mean(outercv_test_results$absolute_error), digits = 2),
                          " (\u00B1 ", round(sd(outercv_test_results$absolute_error), digits = 2), 
                          ")"),
           hjust = 0, vjust = 2,
           check_overlap = TRUE)+
  theme_bw()

# e
```

```{r fig.width=8.25, fig.height=4, message=FALSE}
ggarrange(c, e, nrow=1, labels=c("A", "B"))
```

```{r fig.width=6, fig.height=10, warning=FALSE, message=FALSE}
## for supp
supp <- ggplot(pheno_outercv %>% 
                 mutate(data_split = factor(data_split, levels=c("Training data", "Test data"))), 
               aes(x=age, y=predicted_age))+
  geom_point(alpha = 0.5) + 
  geom_smooth(method = "lm") +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "grey")+
  lims(x=c(min_val, max_val),
       y=c(min_val, max_val))+
  facet_grid(iteration~data_split)+
  labs(x = "Observed age (years)", y = "Predicted age (years)") +
  theme_bw()+
  stat_regline_equation(label.x.npc = "left", label.y.npc = "top")
  # stat_cor(label.x.npc = "left", label.y.npc = "top", method = "pearson", ## option for R and p
  #          aes(label = paste(after_stat(rr.label), after_stat(p.label), sep = "~`,`~")))

# supp
```

```{r fig.width=3.5, fig.height=10, warning=FALSE, message=FALSE}
## for supp
supp2 <- ggplot(pheno_outercv %>% 
                  mutate(data_split = factor(data_split, levels=c("Training data", "Test data"))), 
                aes(x=data_split, y=absolute_error))+
  geom_boxplot(fill = "#3366FF", aes(alpha=data_split))+
  geom_jitter(alpha = 0.5, width=0.3) + 
  lims(y=c(0, 1))+
  facet_grid(iteration~.)+
  labs(x = "", y = "Absolute error (years)") +
  theme_bw()+
  geom_text(aes(x=data_split, y=1, 
                label = paste0("MAE: ", round(mae, digits=2))),
            check_overlap = TRUE, 
            size=3)+
  theme(legend.position = "none")

# supp2
```

```{r fig.width=8.25, fig.height=10.5, warning=FALSE, message=FALSE}
ggarrange(supp, supp2+ggtitle(""), widths=c(0.66, 0.33), labels=c("A", "B"))
```

```{r}
ggsave("figuresTables/5foldcv_supp.png", width=8.25, height=10.5)
```

```{r}
## END SCRIPT
```